name: steam_auth
description: A Dart library providing Steam Mobile Authenticator functionality
version: 0.0.1
author: Teslim Olunlade <tolunlade@outlook.com>
homepage: https://github.com/ogtega/steam_auth

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:

